
version : '3.0' # 도커 컴포즈의 버전을 3.0으로 지정한다.
services: # 컨테이너에서 진행할 정보들을 service아래에 작성한다.
  test: # test라는 이름의 컨테이너를 정의한다.
    image: opsop:3.0 # 이미지의 태그를 opsop:3.0으로 지정한다.
    build: . # 현재 위치를 가리키는 . 을 build에 지정하여 도커파일의 경로를 지정한다.
    ports:
      - "80:80" # 포트를 80과 80을 매핑해준다.